# Generated by Django 6.1 on 2026-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_earnings', models.DecimalField(decimal_places=2, default=14890.0, max_digits=12)),
                ('weekly_earnings_growth', models.DecimalField(decimal_places=2, default=12.5, max_digits=5)),
                ('total_sales_count', models.IntegerField(default=6547)),
                ('total_sales_growth', models.DecimalField(decimal_places=2, default=8.3, max_digits=5)),
                ('purchased_goods_count', models.IntegerField(default=1478)),
                ('purchased_goods_growth', models.DecimalField(decimal_places=2, default=-2.1, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3-letter code (e.g. USA, CHN, IDN)', max_length=10)),
                ('country_name', models.CharField(max_length=100)),
                ('sales_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('time_range', models.CharField(choices=[('week', 'This Week'), ('month', 'This Month'), ('quarter', 'This Quarter'), ('year', 'This Year')], default='week', max_length=20)),
                ('color_tier', models.CharField(default='navy', help_text="'navy' or 'orange'", max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sales by Countries',
                'unique_together': {('country_code', 'time_range')},
            },
        ),
    ]
