# Generated by Django 6.1 on 2026-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('vehicle_requested', models.CharField(max_length=150)),
                ('rental_days', models.IntegerField(default=1)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lead_score', models.IntegerField(default=85)),
                ('lead_tier', models.CharField(choices=[('High', 'High Lead Score'), ('Medium', 'Medium Lead Score'), ('Low', 'Low Lead Score')], default='High', max_length=20)),
                ('ai_score_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('booking.created', 'booking.created'), ('lead.qualified', 'lead.qualified'), ('inventory.alert', 'inventory.alert'), ('webhook.dispatched', 'webhook.dispatched')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('lead_score', models.IntegerField(blank=True, null=True)),
                ('lead_tier', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('200 OK', '200 OK'), ('Pending', 'Pending'), ('Queued', 'Queued'), ('Failed', 'Failed')], default='200 OK', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
